# Generated by Django 4.2.5 on 2023-10-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad de medida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio unitario')),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.categoria')),
            ],
        ),
    ]
