# Generated by Django 4.2.5 on 2023-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad por unidad'),
        ),
    ]
