# Generated by Django 4.2.5 on 2023-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_tienda_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
