# Generated by Django 4.2.5 on 2023-10-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_tienda_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='categoria',
            new_name='tipo_categoria',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
